### PR TITLE
Fix namespaces

### PR DESCRIPTION
**Pull request by w0rm**
Did code style fixes on top of @ghetolay code.

Still missing image tests, for this I would like to get an example of simple svg sources that do not work with current version of svgstore. @ghetolay are you able to give me an example?

### CODE REVIEW

**Comment by ghetolay** [comment]
What about the one I already used on the tests ? 
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 50 50">
    <rect id="a" width="50" height="10"/>
    <use y="20" xlink:href="#a"/>
    <use y="40" xlink:href="#a"/>
</svg>
```

**Comment by w0rm** [comment]
@ghetolay can you bundle a page with embedded svgstore result that is not working because of missing namespaces? I would like to have an example close to real-world scenario. You can put something on codepen.io or similar resource, this would be helpful. I'm really trying to understand what is the meaning of [namespaces in html5](http://www.w3.org/TR/2011/WD-html5-20110405/namespaces.html) and it seems that it is different from xml.

**Comment by ghetolay** [comment]
Well I also came across that, sometimes it works and sometimes it doesn't :)
From my test when svg is external to the page it doesn't work, I guess it's related to some sort of context. 
From your link I understand that this list of namespace are automatically resolved inside an html5 page. If we remove the svg namespace it [still works](http://codepen.io/anon/pen/gaPovg).   
So you may try 
- a namespace not on the list  
   I don't know any usable on an svg file.
- use 2 files like :  

svg :
```
<svg xmlns="http://www.w3.org/2000/svg">
    <symbol id="namespace" viewBox="0 0 50 50">
        <path id="namespace--a" d="M0 0h50v10H0z"/>
        <use y="20" xlink:href="#namespace--a"/>
        <use y="40" xlink:href="#namespace--a"/>
    </symbol>
</svg>
```
html :

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <svg><use xlink:href="test.svg#namespace"></svg>
  </body>
</html>
```

You may know it but you won't be able to test with ```file://``` protocol, browser will complain about svg not having same protocol as source page. It's also why I can't create a codepen, html and svg both must be serve by same protocol, port and domain name.

*Not related to svgstore* : If you use an `````` tag to import svg with missing namespace, it will also fail.

**Comment by ghetolay** [comment]
Here is a live example : 

https://imbasoft.fr/tests/gulpsvgstore_namespace/

Source : 
https://imbasoft.fr/tests/gulpsvgstore_namespace/src/test.svg

gulpfile : 
https://imbasoft.fr/tests/gulpsvgstore_namespace/gulpfile.js

**Comment by w0rm** [comment]
@ghetolay aha! So it is not broken when it is inside html5, because it doesn't care about namespaces, but when svg is an external one, it becomes an xml document with strict policy regarding namespaces.

**Comment by w0rm** [comment]
@ghetolay thanks for the example, I added it to the test. Will release the new version soon!
0004screenshot

**Comment by w0rm** [comment]
@ghetolay just released 5.0.5, thanks for contribution, and sorry for the delay from my side!

**Pull request merged**
