### PR TITLE
Allow setting up the filename via options

### PR DESCRIPTION
**Pull request by bfred-it**
If you're okay with this I can update the readme

### CODE REVIEW

**Comment by w0rm** [comment]
@bfred-it result file name is the name of base directory of the first file by convention. If you need to rename it, pipe it through gulp-rename. [Check the options section](https://github.com/w0rm/gulp-svgstore#options) from the readme.

**Comment by bfred-it** [comment]
aaah, right! Better :)

**Comment by w0rm** [comment]
@bfred-it you can change the readme if you find it unclear

**Comment by bfred-it** [comment]
I was about to but then I noticed you actually mention gulp-rename already, so we're good. I hadn't read the readme recently

**Pull request closed without merging**
